force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <description>produtos vendidos pela Nunes Sports</description>
    <label>Produto</label>
    <nameField>
        <label>Nome de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto__c/fields/Codigo_Produto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Produto__c</fullName>
    <description>Numeração automática de registro do produto na base de dados</description>
    <displayFormat>NS-{0000}</displayFormat>
    <label>Código</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Produto__c/fields/Descricao_Produto__c.field-meta.xml
<CustomField>
    <fullName>Descricao_Produto__c</fullName>
    <description>Campo disponível para incluir detalhes do produto.</description>
    <label>Descrição</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Produto__c/fields/Preco_Produto__c.field-meta.xml
<CustomField>
    <fullName>Preco_Produto__c</fullName>
    <description>Campo disponível para incluir preço do produto.</description>
    <label>Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProdutoController.cls
public with sharing class ProdutoController {
    @AuraEnabled(cacheable=true)
    public static List<Produto__c> getProdutos() {
        try {
            return [SELECT Id, Name, Preco_Produto__c, Descricao_Produto__c, Codigo_Produto__c FROM Produto__c Limit 10000];
        } catch (Exception e) {
            throw new AuraHandledException('Erro ao buscar produtos: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteProduto(Id productId) {
        try {
            Produto__c produto = [SELECT Id FROM Produto__c WHERE Id = :productId LIMIT 1];
            delete produto;
        } catch (Exception e) {
            throw new AuraHandledException('Erro ao excluir produto: ' + e.getMessage());
        }
    }
}